Repository flox/flox, pull requests merged in 2024-02, with the labels that each got.

#693 feat: rich error messages for environment operations
  cli/flox-rust-sdk/src/models/environment/core_environment.rs
  cli/flox-rust-sdk/src/models/environment/managed_environment.rs
  cli/flox-rust-sdk/src/models/environment/mod.rs
  cli/flox-rust-sdk/src/models/environment/path_environment.rs
  cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
  cli/flox-rust-sdk/src/models/lockfile.rs
  cli/flox/src/commands/environment.rs
  cli/flox/src/main.rs
  cli/flox/src/utils/errors.rs
  cli/flox/src/utils/mod.rs
  cli/tests/environment-containerize.bats
Labels: team-cli

#967 fix: provide exlicit owner and email to git
  cli/flox-rust-sdk/src/providers/git.rs
Labels: bug, team-cli

#983 feat: add 'just clean' target
  Justfile
Labels: team-cli

#1076 fix: typo in workflow
  .github/workflows/lint.yml
Labels: bug

#1081 fix: code clean up and performance fixes
  pkgdb/include/flox/pkgdb/write.hh
  pkgdb/src/flox-flake.cc
  pkgdb/src/pkgdb/write.cc
Labels: enhancement, team-cli

#1082 fix: scrape performance on mac
  pkgdb/src/util.cc
Labels: team-cli
